### ISSUE TITLE
Exception when loading fop

### ISSUE THREAD

**Issue by sgjohnston** [opentorah/opentorah#113]
@dubinsky one other issue I've seen, which is really cosmetic: when fop is class loaded, an exception is thrown (at least on my systems):

org.xml.sax.SAXNotSupportedException: http://xml.org/sax/features/external-general-entities
        at com.icl.saxon.aelfred.SAXDriver.setFeature(SAXDriver.java:451)
        at com.icl.saxon.aelfred.SAXParserFactoryImpl.setFeature(SAXParserFactoryImpl.java:28)
        at org.apache.batik.dom.util.SAXDocumentFactory.<clinit>(SAXDocumentFactory.java:403)
        at org.apache.fop.image.loader.batik.PreloaderSVG$Loader.getImage(PreloaderSVG.java:127)
        at org.apache.fop.image.loader.batik.PreloaderSVG$Loader.access$200(PreloaderSVG.java:108)
        at org.apache.fop.image.loader.batik.PreloaderSVG.preloadImage(PreloaderSVG.java:76)
        at org.apache.xmlgraphics.image.loader.ImageManager.preloadImage(ImageManager.java:176)
        at org.apache.xmlgraphics.image.loader.cache.ImageCache.needImageInfo(ImageCache.java:127)
        at org.apache.xmlgraphics.image.loader.ImageManager.getImageInfo(ImageManager.java:123)
        at org.apache.fop.fo.flow.ExternalGraphic.bind(ExternalGraphic.java:81)
        at org.apache.fop.fo.FObj.processNode(FObj.java:131)
        at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:293)
        at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
        at net.sf.saxon.event.ContentHandlerProxy.startElement(ContentHandlerProxy.java:366)
        at net.sf.saxon.event.ProxyReceiver.startElement(ProxyReceiver.java:132)
        at net.sf.saxon.event.SequenceNormalizer.startElement(SequenceNormalizer.java:84)
        at net.sf.saxon.event.ReceivingContentHandler.startElement(ReceivingContentHandler.java:371)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:439)
        at net.sf.saxon.event.Sender.send(Sender.java:168)
        at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:368)
        at org.opentorah.xml.Saxon.transform(Saxon.scala:135)
        at org.opentorah.xml.Saxon.transform(Saxon.scala:70)
        at org.opentorah.fop.Fop$.run(Fop.scala:110)
        at org.opentorah.fop.Fop$.run(Fop.scala:73)
        at org.opentorah.docbook.plugin.ProcessDocBook.run(ProcessDocBook.scala:81)
...etc

it's caused by org.apache.batik.dom.util.SAXDocumentFactory trying to set an XML parser feature, that can't be set for some reason. Are you aware of any way to control this? As I say, it's cosmetic, as the exception is caught and no harm done, it's just a bit annoying. It doesn't appear to be caused by any of your plugin code at all.

**Comment by dubinsky** [comment]
@sgjohnston 

I saw this, but it doesn't reproduce for me every time (I suspect that Gradle daemon caches loaded classes).

> exception is caught and no harm done

I am not so sure about that.

> It doesn't appear to be caused by any of your plugin code at all

It kind of is: I have to counter-act some classpath magic... I did it before for SVG produced by MathJax from formulas, but not for SVG coming from anywhere else. Pull request https://github.com/opentorah/opentorah/pull/115 has more information. Let's see if the patched version (still v0.7.51) fixes this for you :)

**Comment by sgjohnston** [comment]
Yes, once the gradle daemon starts, and the class is loaded, it stays "live" until it's shut down, so you only see the exception each time the daemon starts. You can reliably reproduce it by stopping the daemon first, or running without it (gradle --no-daemon).

Anyway, #115 fixes it, no exception thrown.

Thanks!

**Comment by dubinsky** [comment]
Great, thanks! Closing.
